version: "3"

services:
  caddy:
    image: caddy:latest
    container_name: caddy_static_server
    ports:
      - "8999:8999"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./sites:/srv/sites
    restart: always

